# Generated by Django 3.1.6 on 2021-02-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(default='', max_length=100)),
                ('weather', models.CharField(default='', max_length=100)),
                ('keywords', models.CharField(default='', max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
